### ISSUE TITLE
Link to XF2 version in XFRM item's FAQ

### ISSUE THREAD

**Issue by Xon** [Fuhrmann/xenforo-who-replied#11]
I've had this add-on ported to XF2, could you add an FAQ entry pointing to it?
https://xenforo.com/community/resources/who-replied.6340/

FYI; I've also got a v1.6.0 which backports the username filtering to XF1 version. Needs some cleanup

**Comment by Fuhrmann** [comment]
Done! 44146f34e89597984422bf74de4df82b0c9ccf10

Thanks Xon!

**Comment by Fuhrmann** [comment]
I updated here to: https://xenforo.com/community/resources/who-replied.1537/
