### ISSUE TITLE
Release v1.6.0 on xenforo.com

### ISSUE THREAD

**Issue by Xon** [Fuhrmann/xenforo-who-replied#12]
Changes from v1.5.2 release:
- Add username filtering/searching to "Who Replied?" dialog.
- Ensure stable sorting when paging through the result set
- Setup default permissions on registered usergroup on first install
- Remove permissions when uninstalled
- Display more profile information (support Post Ratings)
- Display "Start conversation link" if privacy options permit
- Only render search link if the user is permitted to search.
- Ensure search link generates a date sorted search

**Comment by Xon** [comment]
The v1.6.0 part are quite small and I'm happy with them, might as well kick it to XFRM :)

zip URL; https://github.com/Fuhrmann/xenforo-who-replied/releases/download/v1.6.0/addon-Fuhrmann-WhoReplied-1.6.0.zip

**Comment by Fuhrmann** [comment]
This is great. Thanks again for your work. Could you please confirm, what's the supported version of XenForo? It's still the same versions in the readme file?  I'll upload the release to XenForo.

**Comment by Fuhrmann** [comment]
Done! https://xenforo.com/community/resources/who-replied.1537/updates#resource-update-25838

**Comment by Xon** [comment]
@Fuhrmann yeah same as the readme file. the installer just enforces the minimum version now.
